name: run-gradle-container 
on: push
jobs:
  Clone:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./ci/build-app.sh
